### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by martinvenus** [Spoje-NET/FlexiPeeHP#14]
Bylo by prosím možné upravit požadovanou verzi PHP tak, aby bylo možné použít i PHP 7.3?

**Comment by Vitexus** [comment]
Dobrý den, to nebude problém. Jinak předpokládm že kromě protestujícího composeru jste se žádnými problémy nesetkal ?

**Comment by martinvenus** [comment]
Dobrý den, zatím jsem to důkladně nevyzkoušel, ale na první pokus žádný problém. Určitě to ještě důkladně vyzkouším.

**Comment by Vitexus** [comment]
Až mi @martinvenus  potrvrdí že s aktualizací a použitím knihovny po ní není problém toto issue uzavřu. Release by mohlo být v dohledné době.

**Comment by martinvenus** [comment]
Vyzkoušel jsem vše co používáme (přijaté faktury, vydané faktury, střediska a zakázky) a vše funguje bez problémů.

**Comment by martinvenus** [comment]
Ještě je potřeba upravit "vitexsoftware/ease-framework" tak, aby bylo možné použít PHP 7.3.

**Comment by Vitexus** [comment]
PHP 7.3.0beta2 (cli) (built: Sep 10 2018 10:05:14) ( NTS )
===============================================

Dokud nebude release, tak budete muset composer donutit používat vývojové verze - composer.json:
```json
{
    "name": "vitex/flexipeehp73",
    "description": "Test",
    "type": "project",
    "require": {
        "spoje.net/flexipeehp": "dev-master"
    },
    "license": "MIT",
    "authors": [
        {
            "name": "Cybervitexus",
            "email": "info@vitexsoftware.cz"
        }
    ],
    "minimum-stability": "dev"
}
```
Nainstaluje se:
```
vitex@novolen:~/tmp/flexipeehp73$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing pear/pear_exception (dev-master 8c18719): Cloning 8c18719fda from cache
  - Installing pear/console_getopt (v1.4.1): Loading from cache
  - Installing pear/pear-core-minimal (v1.10.6): Loading from cache
  - Installing pear/mail_mime (1.10.2): Loading from cache
  - Installing pear/mail (v1.4.1): Loading from cache
  - Installing vitexsoftware/ease-framework (dev-master edc9060): Cloning edc9060cb1 from cache
  - Installing spoje.net/flexipeehp (dev-master c9fc136): Cloning c9fc136d17 from cache
pear/mail suggests installing pear/net_smtp (Install optionally via your project's composer.json)
Writing lock file
Generating autoload files
```
