### ISSUE TITLE
Undefined index notice v FlexiBeeRO

### ISSUE THREAD

**Issue by petaak** [Spoje-NET/FlexiPeeHP#17]
Od nové verze 1.28 nastává při zavolání metody Banka::automatickeParovani na řádku 1044 v třídě FlexiBeeRO notice o undefined indexu.
`PHP Notice: Undefined index: banka in /var/www/html/vendor/spoje.net/flexipeehp/src/FlexiPeeHP/FlexiBeeRO.php:1044`

**Comment by Vitexus** [comment]
Díky za bugrport!
Prosím vydržte, podívám se na to.

**Comment by Vitexus** [comment]
Prosím vás @petaak stačí vám ta oprava takto nebo potřebujete release ? 

p.s.
A jestli mi chcete udělat radost tak se pochlubte, kde vám to běží. Pokud to bude veřejné tak se pak budu zase mít čím chubit já, kdo všechno a v čem používá mojí knihovnu ;)

**Comment by petaak** [comment]
Díky, takto stačí, na další release si počkáme.

p.s.
Napsal jsem e-mail.
