### ISSUE TITLE
Strict standards FlexiPeeHP/Formats

### ISSUE THREAD

**Issue by jbrada** [Spoje-NET/FlexiPeeHP#4]
Ve třídě FlexiPeeHP/Formats způsobí volání metody \Ease\Sand::reindexArrayBy metodami byContentType() a bySuffix() vyvolání chyby 

> Non-static method should not be called statically

* E_STRICT v PHP 5 
* E_DEPRECATED v PHP 7

**Comment by Vitexus** [comment]
Dobrý den, 
o tato chyba byla už před nějakou dobou opravena. Opravdu používáte nejnovější verze ?

Aktuálně je funkce definovaná jako:
    public static function reindexArrayBy($data, $indexBy = null)

viz:
https://github.com/VitexSoftware/EaseFramework/blob/c98e13412ef199b994f56a99eeccf016a1779021/src/Ease/Sand.php#L686

takže by neměl být problém volat         return \Ease\Sand::reindexArrayBy(self::$formats, 'content-type');

Napište mi případně jak knihovny používáte jesli přez composer nebo jinak a případnou chybku pořešíme.

p.s. Díky za bugreport

**Comment by jbrada** [comment]
Není zač :). Knihovnu instaluji přes composer, který defaultně s "minimum-stability": "stable" stáhne poslední release a ne aktuální commit z masteru.

Vypadá to, že [commit,](https://github.com/VitexSoftware/EaseFramework/commit/e1c4ca52f1ffe56b1246dd46c06716965b9c0103) který přidává funkcím static není zahrnutý v poslední release  VitexSoftware/EaseFramework (1.2.3).

**Comment by Vitexus** [comment]
Vydal jsem tedy release: 

https://github.com/VitexSoftware/EaseFramework/releases/tag/1.3

Napište mi prosím zda to pomohlo.
Děkuji
